from python:3.8
RUN apt-get update && apt-get install -y \
    libpq-dev
workdir /app
copy requirements.txt requirements.txt
Run pip3 install -r requirements.txt
expose 8000
ENTRYPOINT python -m debugpy --listen 0.0.0.0:9087 manage.py runserver 0.0.0.0:8000
