version: "3.8"

services:
  hope_ui:
    build:
      context: ${UI_FOLDER}
      dockerfile: ${API_FOLDER}/Infra/Dockerfile.ui
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ${UI_FOLDER}:/app
      - node_modules:/app/node_modules
    restart: always
    networks:
      - hope
    container_name: hope_ui

  hope_backend:
    build:
      context: ${API_FOLDER}
      dockerfile: ${API_FOLDER}/Infra/Dockerfile.api
    ports:
      - "8000:8000"
    volumes:
      - ${API_FOLDER}:/app
    depends_on:
      - postgres
    restart: always
    networks:
      - hope
    container_name: hope_backend

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ${DB_FOLDER}:/var/lib/postgresql/data/ #this is to save your data when you close your containers
      - ${API_FOLDER}/Infra/seed.sql:/tmp/seed.sql
    networks:
      - hope
    container_name: postgres
    
    
volumes:
  node_modules:
networks:
  hope:
    name: hope
    driver: bridge

